name: Build and push docker images to private registry

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .  
          push: false   
          tags: |
            docker-test:docker-frontend-invest
            docker-test:c71f2500
          file: ./dockerfile

      - name: Log in to Private Docker Registry
        uses: docker/login-action@v2
        with:
          registry: localhost:5000   
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push Docker Image to Private Registry
        run: |
          docker tag docker-test:docker-frontend-invest localhost:5000/my-repo/docker-test:docker-frontend-invest
          docker tag docker-test:c71f2500 localhost:5000/my-repo/docker-test:c71f2500
          docker push localhost:5000/my-repo/docker-test:frontend-invest
          docker push localhost:5000/my-repo/docker-test:c71f2500
