name: Build, Push and Deploy Docker Image

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker image tag
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u deepuprajapat --password-stdin

      - name: Build Docker image
        run: |
          docker build -f Dockerfile \
            -t ghcr.io/deepuprajapat/im-frontend:${{ env.TAG }} \
            -t ghcr.io/deepuprajapat/im-frontend:latest .

      - name: Push Docker image
        run: |
          docker push ghcr.io/deepuprajapat/im-frontend:${{ env.TAG }}
          docker push ghcr.io/deepuprajapat/im-frontend:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            IMAGE_TAG=${{ env.TAG }}
            echo "Deploying IM Frontend with image tag: $IMAGE_TAG"

            # Login to GHCR on EC2
            echo "${{ secrets.GHCR_PAT }}" | sudo docker login ghcr.io -u deepuprajapat --password-stdin

            # Navigate to project directory
            cd ~/IM-Frontend || exit 1

            # Pull the new Docker image
            sudo docker pull ghcr.io/deepuprajapat/im-frontend:$IMAGE_TAG
            sudo docker pull ghcr.io/deepuprajapat/im-frontend:latest

            # Create .env file with tag
            echo "IMAGE_TAG=$IMAGE_TAG" > .env

            # Stop previous containers
            sudo docker compose down

            # Recreate containers with latest image
            sudo docker compose up -d --pull always --force-recreate
